# Generated by Django 3.2.5 on 2021-07-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petifyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCenter',
            fields=[
                ('centerid', models.AutoField(primary_key=True, serialize=False)),
                ('centername', models.CharField(max_length=50)),
                ('centerlocation', models.CharField(max_length=100)),
                ('centerpincode', models.IntegerField(max_length=6)),
                ('centerphone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
