# Generated by Django 3.2.5 on 2021-07-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petifyapp', '0003_vaccinationcenter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='centerphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='centerpincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='image',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
